platform :ios, '9.0'

target 'JitEat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PromiseKit/CorePromise', '~> 6.0'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
end
