platform :ios, '10.0'

target 'JitEat' do
  use_frameworks!

  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'

  pod 'MaterialComponents'
end
